version: '3'
services:
  default-db-dev:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=${DEFAULT_DB_USER}
      - MYSQL_PASSWORD=${DEFAULT_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DEFAULT_DB_PASSWORD}
      - MYSQL_DATABASE=${DEFAULT_DB_NAME:-django_catalog_api}
    ports:
      - "${DEFAULT_DB_HOST:-127.0.0.1}:${DEFAULT_DB_PORT:-3306}:3306"
    volumes:
      - ./docker_data/default_db_dev:/var/lib/mysql
    networks:
      - development
    user: ${USERID}:${GROUPID}
    command: mysqld --wait_timeout=7200

  default-db-test:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=${TEST_DEFAULT_DB_USER}
      - MYSQL_PASSWORD=${TEST_DEFAULT_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TEST_DEFAULT_DB_PASSWORD}
      - MYSQL_DATABASE=${TEST_DEFAULT_DB_NAME:-capi_test}
    ports:
      - "${TEST_DEFAULT_DB_HOST:-127.0.0.1}:${TEST_DEFAULT_DB_PORT:-3307}:3306"
    volumes:
      - ./docker_data/default_db_test:/var/lib/mysql
    networks:
      - testing
    user: ${USERID}:${GROUPID}
    command: mysqld --wait_timeout=7200

  sierra-db-test:
    image: postgres:9.2
    environment:
      - POSTGRES_USER=${TEST_SIERRA_DB_USER}
      - POSTGRES_PASSWORD=${TEST_SIERRA_DB_PASSWORD}
      - POSTGRES_DB=${TEST_SIERRA_DB_NAME:-sierra_test}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${TEST_SIERRA_DB_HOST:-127.0.0.1}:${TEST_SIERRA_DB_PORT:-5432}:5432"
    volumes:
      - ./docker_data/sierra_db_test:/var/lib/postgresql/data/pgdata
    networks:
      - testing
    user: ${USERID}:${GROUPID}

  solr-dev:
    image: openjdk:8-jre
    volumes:
      - ./solr:/project/solr
      - ./docker_data/solr_dev/logs:/project/solr/instances/logs
      - ./docker_data/solr_dev/bibdata_data:/project/solr/instances/solr/bibdata/data
      - ./docker_data/solr_dev/haystack_data:/project/solr/instances/solr/haystack/data
      - ./docker_data/solr_dev/marc_data:/project/solr/instances/solr/marc/data
      - ./docker_data/solr_dev/blacklight-dev-01_data:/project/solr/instances/solr/blacklight-dev-01/data
      - ./docker_data/solr_dev/bl-demo_data:/project/solr/instances/solr/bl-demo/data
    working_dir: /project/solr/instances
    ports:
      - "${SOLR_HOST:-127.0.0.1}:${SOLR_PORT:-8983}:8983"
    networks:
      - development
    user: ${USERID}:${GROUPID}
    command: java -jar /project/solr/instances/start.jar -Djetty.port=8983

  solr-test:
    image: openjdk:8-jre
    volumes:
      - ./solr:/project/solr
      - ./docker_data/solr_test/logs:/project/solr/instances/logs
      - ./docker_data/solr_test/bibdata_data:/project/solr/instances/solr/bibdata/data
      - ./docker_data/solr_test/haystack_data:/project/solr/instances/solr/haystack/data
      - ./docker_data/solr_test/marc_data:/project/solr/instances/solr/marc/data
      - ./docker_data/solr_test/blacklight-dev-01_data:/project/solr/instances/solr/blacklight-dev-01/data
      - ./docker_data/solr_dev/bl-demo_data:/project/solr/instances/solr/bl-demo/data
    working_dir: /project/solr/instances
    ports:
      - "${TEST_SOLR_HOST:-127.0.0.1}:${TEST_SOLR_PORT:-8883}:8983"
    networks:
      - testing
    user: ${USERID}:${GROUPID}
    command: java -jar /project/solr/instances/start.jar -Djetty.port=8983

  redis-celery:
    image: redis:3.2
    volumes:
      - ./docker_data/redis_celery/data:/project/data
      - ./docker_data/redis_celery/logs:/project/logs
    ports:
      - "${REDIS_CELERY_HOST:-127.0.0.1}:${REDIS_CELERY_PORT:-6379}:6379"
    networks:
      - testing
      - development
    user: ${USERID}:${GROUPID}
    command: redis-server ${REDIS_CELERY_CONF_FILE:---dir /project/data --logfile /project/logs/log.txt --appendonly yes}

  redis-appdata-dev:
    image: redis:3.2
    volumes:
      - ./docker_data/redis_appdata_dev/data:/project/data
      - ./docker_data/redis_appdata_dev/logs:/project/logs
    ports:
      - "${REDIS_APPDATA_HOST:-127.0.0.1}:${REDIS_APPDATA_PORT:-6380}:6379"
    networks:
      - development
    user: ${USERID}:${GROUPID}
    command: redis-server ${REDIS_APPDATA_CONF_FILE:---dir /project/data --logfile /project/logs/log.txt --appendonly yes}

  redis-appdata-test:
    image: redis:3.2
    volumes:
      - ./docker_data/redis_appdata_test/data:/project/data
      - ./docker_data/redis_appdata_test/logs:/project/logs
    ports:
      - "${TEST_REDIS_APPDATA_HOST:-127.0.0.1}:${TEST_REDIS_APPDATA_PORT:-6280}:6379"
    networks:
      - testing
    user: ${USERID}:${GROUPID}
    command: redis-server ${REDIS_APPDATA_CONF_FILE:---dir /project/data --logfile /project/logs/log.txt --appendonly yes}

  app:
    build:
      context: .
      args:
        userid: ${USERID}
        groupid: ${GROUPID}
    depends_on:
      - default-db-dev
      - solr-dev
      - redis-appdata-dev
    volumes:
      - .:/project/catalog-api
      - ./docker_data/app/logs:/project/logs
      - ./docker_data/app/media:/project/media
    working_dir: /project/catalog-api/django/sierra
    networks:
      - testing
      - development
    ports:
      - "0.0.0.0:${DJANGO_PORT:-8000}:8000"
    command: wait-for-it.sh -t 30 default-db-dev:3306 -- wait-for-it.sh -t 30 solr-dev:8983 -- wait-for-it.sh -t 30 redis-appdata-dev:6379 -- /project/catalog-api/django/sierra/manage.py runserver 0.0.0.0:8000

  celery-worker:
    build:
      context: .
      args:
        userid: ${USERID}
        groupid: ${GROUPID}
    depends_on:
      - default-db-dev
      - redis-celery
    volumes:
      - .:/project/catalog-api
      - ./docker_data/celery_worker/logs:/project/logs
    working_dir: /project/catalog-api/django/sierra
    networks:
      - testing
      - development
    command: wait-for-it.sh -t 30 default-db-dev:3306 -- wait-for-it.sh -t 30 redis-celery:6379 -- celery worker -A sierra -c 4 -l info -f /project/logs/celery-worker.log

  test:
    build:
      context: .
      args:
        userid: ${USERID}
        groupid: ${GROUPID}
    depends_on:
      - default-db-test
      - sierra-db-test
      - solr-test
      - redis-appdata-test
    volumes:
      - .:/project/catalog-api
      - ./docker_data/test/logs:/project/logs
      - ./docker_data/test/media:/project/media
    environment:
      - SOLRMARC_CONFIG_FILE=${TEST_SOLRMARC_CONFIG_FILE:-test_config.properties}
      - SOLRMARC_COMMAND=/project/catalog-api/solr/solrmarc/indexfile.sh
    working_dir: /project/catalog-api/
    networks:
      - testing
    entrypoint: wait-for-it.sh -t 30 default-db-test:3306 -- wait-for-it.sh -t 30 sierra-db-test:5432 -- wait-for-it.sh -t 30 solr-test:8983 -- wait-for-it.sh -t 30 redis-appdata-test:6379 -- py.test

  manage-dev:
    build:
      context: .
      args:
        userid: ${USERID}
        groupid: ${GROUPID}
    depends_on:
      - default-db-dev
    volumes:
      - .:/project/catalog-api
      - ./docker_data/app/logs:/project/logs
      - ./docker_data/app/media:/project/media
    networks:
      - development
    working_dir: /project/catalog-api/django/sierra
    entrypoint: wait-for-it.sh -t 30 default-db-dev:3306 -- /project/catalog-api/django/sierra/manage.py

  manage-test:
    build:
      context: .
      args:
        userid: ${USERID}
        groupid: ${GROUPID}
    depends_on:
      - default-db-test
      - sierra-db-test
    volumes:
      - .:/project/catalog-api
      - ./docker_data/test/logs:/project/logs
      - ./docker_data/test/media:/project/media
    networks:
      - testing
    working_dir: /project/catalog-api/django/sierra
    environment:
      - DJANGO_SETTINGS_MODULE=sierra.settings.test
      - SOLRMARC_CONFIG_FILE=${TEST_SOLRMARC_CONFIG_FILE:-test_config.properties}
    entrypoint: wait-for-it.sh -t 30 default-db-test:3306 -- wait-for-it.sh -t 30 sierra-db-test:5432 -- /project/catalog-api/django/sierra/manage.py

networks:
  development:
  testing:
